- name: Deploy vault
  hosts: all

  tasks:
    - name: Deploy Vault
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - jq
        - curl
        - sudo
        - gpg
        - software-properties-common

    - name: Add HashiCorp GPG key
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present
        
    - name: Add HashiCorp repository
      apt_repository:
        repo: deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
        state: present
    
    - name: Install Vault
      apt:
        name: vault
        state: present
        update_cache: yes

    - name: Add acmerunner ssh key to root
      ansible.posix.authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', 'files/acme_id_rsa.pub') }}"
        exclusive: no

    - name: Create vault configuration
      template:
        src: templates/vault-config.hcl
        dest: /etc/vault.d/vault.hcl
        owner: root
        group: root
        mode: 0644
      
    - name: Create key directory
      file:
        path: /etc/vault.d/keys
        state: directory
        owner: root
        group: root
        mode: 0700

    - name: Create vault unseal script
      copy:
        src: post_start.sh
        dest: /etc/vault.d/post_start.sh
        mode: 0700
        owner: root
        group: root

    - name: Create vault keys file  
      copy:
        src: keys.json
        dest: /etc/vault.d/keys/keys.json
        mode: 0600
        owner: root
        group: root
        

